// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALiZz1tCe1Bc0TaLuYtcRNF5i-q-naW2s',
    appId: '1:1002130893277:web:b8c8f669b1f4c58ad42e34',
    messagingSenderId: '1002130893277',
    projectId: 'flutter-dennis-pizza',
    authDomain: 'flutter-dennis-pizza.firebaseapp.com',
    storageBucket: 'flutter-dennis-pizza.firebasestorage.app',
    measurementId: 'G-KP61SX5Y6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkLTOn26ROCR0-6pwmGJaFmUcv_c5s4o8',
    appId: '1:1002130893277:android:5a63d82a0b60f293d42e34',
    messagingSenderId: '1002130893277',
    projectId: 'flutter-dennis-pizza',
    storageBucket: 'flutter-dennis-pizza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxywLMrqMqbY218igNGsHoW7ycU4g0Pmo',
    appId: '1:1002130893277:ios:121044bc291a30e5d42e34',
    messagingSenderId: '1002130893277',
    projectId: 'flutter-dennis-pizza',
    storageBucket: 'flutter-dennis-pizza.firebasestorage.app',
    iosBundleId: 'com.techupstudio.spar',
  );

}